#BSUB -n 2
#BSUB -J "hybrid_nonblock_2p_4t_400_600"
#BSUB -o "hybrid_nonblock_2p_4t_400_600%J.out"
#BSUB -e "hybrid_nonblock_2p_4t_400_600%J.err"
#BSUB -R "affinity[core(4)]"
# Загрузка модуля OpenMPI
module load OpenMPI/4.0.2
# Переход в рабочую директорию
cd $LS_SUBCWD
# Компиляция неблокирующей версии
mpic++ -fopenmp -O3 -o main_hybrid_nonblocking main_hybrid_nonblocking.cpp
# Запуск с неблокирующими операциями MPI
OMP_NUM_THREADS=4 mpirun -np 2 ./main_hybrid_nonblocking 400 600 4




