#BSUB -n 4
#BSUB -J "hybrid_nonblock_4p_1t_800_1200"
#BSUB -o "hybrid_nonblock_4p_1t_800_1200%J.out"
#BSUB -e "hybrid_nonblock_4p_1t_800_1200%J.err"
#BSUB -R "affinity[core(1)]"
# Загрузка модуля OpenMPI
module load OpenMPI/4.0.2
# Переход в рабочую директорию
cd $LS_SUBCWD
# Компиляция неблокирующей версии
mpic++ -fopenmp -O3 -o main_hybrid_nonblocking main_hybrid_nonblocking.cpp
# Запуск с неблокирующими операциями MPI
OMP_NUM_THREADS=1 mpirun -np 4 ./main_hybrid_nonblocking 800 1200 1




